men_team_victoria_2023_stats = {
    "team_name": "Victoria",
    "games_played": 20,
    "points_per_game": 92,
    "field_goal_percentage": 43.3,
    "three_point_percentage": 34.7,
    "free_throw_percentage": 69.2,
    "offensive_rebounds_per_game": 16.2,
    "defensive_rebounds_per_game": 32.4,
    "total_rebounds_per_game": 48.5,
    "field_goal_made": 667,
    "field_goal_attempted": 1541,
    "three_pointers_made": 240,
    "three_pointers_attempted": 692,
    "free_throws_made": 265,
    "free_throws_attempted": 383,
    "assists_per_game": 13.2,
    "turnovers_per_game": 11.8,
    "steals_per_game": 8.7,
    "blocks_per_game": 4.4,
    "team_fouls_per_game": 15.8,
    "offensive_efficiency": 1.118,
    "defensive_efficiency": 0.887,
    "net_efficiency": 0.232,
    "field_goals_percentage_against": 39.9,
    "three_points_percentage_against": 31,
    "offensive_rebounds_per_game_against": 9.9,
    "defensive_rebounds_per_game_against": 29.4,
    "total_rebounds_per_game_against": 39.3,
    "assists_per_game_against": 14.2,
    "turnovers_per_game_against": 17.1,
    "steals_per_game_against": 6.8,
    "blocks_per_game_against": 2.6,
    "team_fouls_per_game_against": 18.4,
    "points_per_game_against": 73.3,
    "field_goal_made_against": 536,
    "field_goal_attempted_against": 1345,
    "three_pointers_made_against": 166,
    "three_pointers_attempted_against": 536,
    "conference": "CW",
    "total_wins": 17,
    "total_losses": 3,
    "win_percentage": 0.85,
    "last_ten_games": "9-1",
    "streak": "W 9",
    "total_points": 1839,
    "total_points_against": 1467,
    # "team_id": 43
}

wbb_player_stats_2023 = {
    "lastname_initials": "E",
    "first_name": "Ougrinov",
    "school": "Toronto",
    "games_played": 22,
    "games_started": 22,
    "minutes_played": 810,
    "offensive_rebounds": 7,
    "defensive_rebounds": 96,
    "total_rebounds": 103,
    "personal_fouls": 67,
    "disqualifications": 3,
    "assists": 55,
    "turnovers": 82,
    "assist_per_turnover": 0.7,
    "steals": 30,
    "blocks": 7,
    "field_goal_made": 121,
    "field_goal_attempted": 374,
    "field_goal_percentage": 32.4,
    "three_pointers_made": 77,
    "three_pointers_attempted": 235,
    "three_pointers_percentage": 32.8,
    "free_throws_made": 75,
    "free_throws_attempted": 93,
    "free_throws_percentage": 80.6,
    "total_points": 394,
    "player_id": 11,
    # "team_id": 33
}
