columns_list = [
    [
        "field_goal_made",
        "field_goal_percentage",
        "three_pointers_made",
        "three_point_percentage",
        "free_throws_made",
        "free_throw_percentage",
        "points_per_game",
    ],
    [
        "offensive_rebounds_per_game",
        "defensive_rebounds_per_game",
        "total_rebounds_per_game",
        "rebound_margin",
    ],
    [
        "turnovers_per_game",
        "steals_per_game",
        "blocks_per_game",
        "assists_per_game",
    ],
    ["team_fouls_per_game", "offensive_efficiency", "net_efficiency"],
    [
        "field_goal_made_against",
        "field_goal_percentage_against",
        "three_pointers_made_against",
        "three_point_percentage_against",
        "points_per_game_against",
    ],
    [
        "offensive_rebounds_per_game_against",
        "defensive_rebounds_per_game_against",
        "total_rebounds_per_game_against",
        "rebound_margin_against",
    ],
    [
        "turnovers_per_game_against",
        "steals_per_game_against",
        "blocks_per_game_against",
        "assists_per_game_against",
    ],
    [
        "team_fouls_per_game_against",
        "defensive_efficiency",
        "net_efficiency_against",
    ],
]

team_conference = {
    'Acadia': 'AUS',
    'Alberta': 'CW',
    'Algoma': 'OUA West',
    'Bishop\'s': 'RSEQ',
    'Brandon': 'CW',
    'Brock': 'OUA Central',
    'Calgary': 'CW',
    'Cape Breton': 'AUS',
    'Carleton': 'OUA East',
    'Concordia': 'RSEQ',
    'Dalhousie': 'AUS',
    'Guelph': 'OUA West',
    'Lakehead': 'OUA Central',
    'Laurentian': 'OUA East',
    'Laurier': 'OUA West',
    'Laval': 'RSEQ',
    'Lethbridge': 'CW',
    'MacEwan': 'CW',
    'Manitoba': 'CW',
    'McGill': 'RSEQ',
    'McMaster': 'OUA Central',
    'Memorial': 'AUS',
    'Mount Royal': 'CW',
    'Nipissing': 'OUA East',
    'Ontario Tech': 'OUA East',
    'Ottawa': 'OUA East',
    'Queen\'s': 'OUA East',
    'Regina': 'CW',
    'Saint Mary\'s': 'AUS',
    'Saskatchewan': 'CW',
    'StFX': 'AUS',
    'Thompson Rivers': 'CW',
    'Toronto': 'OUA Central',
    'Toronto Metropolitan': 'OUA Central',
    'Trinity Western': 'CW',
    'UBC': 'CW',
    'UBC Okanagan': 'CW',
    'UFV': 'CW',
    'UNB': 'AUS',
    'UNBC': 'CW',
    'UPEI': 'AUS',
    'UQAM': 'RSEQ',
    'Victoria': 'CW',
    'Waterloo': 'OUA West',
    'Western': 'OUA West',
    'Windsor': 'OUA West',
    'Winnipeg': 'CW',
    'York': 'OUA Central'
    }

standings_column_list = [
    "games_played",
    "total_wins",
    "total_losses",
    "ties",
    "win_percentage",
    "total_points",
    "total_points_against",
]

stat_group_options = [
        "#sh-0",
        "#rb-0",
        "#bc-0",
        "#eff-0",
        "#dsh-0",
        "#drb-0",
        "#dbc-0",
        "#deff-0",
    ]